import json
import os


def create_song_files(input_filename):
    try:
        with open(input_filename, 'r', encoding='utf-8') as f:
            songs = json.load(f)
    except FileNotFoundError:
        print(f"Error: {input_filename} not found.")
        return

    output_dir = "docs/temp_gen/output_json"
    os.makedirs(output_dir, exist_ok=True)

    for song in songs:
        slug_raw = song.get('slug', 'unknown')
        filename = slug_raw.split('/')[-1] if '/' in slug_raw else slug_raw

        raw_cover = song.get('coverUrl', '')
        processed_cover = raw_cover.replace('/assets/', '').rsplit('.', 1)[0]

        data = {
            "meta": {
                "title": song.get('title'),
                "artist": "ときのそら",
                "originalKey": "Em",
                "capo": "",
                "description": "",
                "composer": song.get('composer'),
                "lyricist": song.get('lyricist'),
                "album": song.get('album'),
                "releaseDate": song.get('releaseDate'),
                "coverUrl": processed_cover,
                "penlight_color": ["#0000ff"],
                "links": [
                    {"name": "Official MV", "url": "https://youtu.be/Xxx"}
                ]
            },
            "chords": [
                {
                    "section": "Intro",
                    "lines": [
                        {"c": "Xxx", "t": "ccc"},
                        {"c": "Xxx", "t": "ccc"}
                        ]
                }
            ],
            "calls": [
                {
                    "lyrics": "aaa",
                    "call": "bbb",
                },
                {
                    "lyrics": "aaa",
                    "call": "bbb",
                }
            ],
            "lyrics": [
                {
                    "ja": "※ただいま歌詞の翻訳はAIによる生成したものです。人工による翻訳は後ほどアップデートする予定です！",
                    "romaji": "",
                    "en": "※This translation is currently generated by AI. The refined version is coming soon!",
                    "zh": "※此翻譯暫時是AI生成的。人工的翻譯會容後更新！"
                },
                {
                    "ja": "明け方の一番星は",
                    "romaji": "Akegata no Ichibanboshi ha",
                    "en": "and the morning star",
                    "zh": "晨曦最亮的星",
                }
            ]
        }

        output_path = os.path.join(output_dir, f"{filename}.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        print(f"Generated: {output_path}")


if __name__ == "__main__":
    create_song_files('song_list.json')